// The pinned language ontology — GitHub Linguist's taxonomy (name · type · slug · color),
// the controlled vocabulary for the `language` axis, mirroring vocabulary.ts (topics).
// A repo's `language` (GitHub's primary-language field) is a Linguist name, so this is
// the canonical reference for normalizing, validating, slugging, and colouring it.
// Source: github-linguist/linguist lib/linguist/languages.yml (regenerate from there).

export type LanguageType = "programming" | "markup" | "data" | "prose" | "nil";
export interface LanguageEntry {
  /** Display name — matches GitHub's `repo.language`. */
  readonly name: string;
  /** Linguist classification. */
  readonly type: string;
  /** URL slug — GitHub's /trending/<slug> convention. */
  readonly slug: string;
  /** Linguist brand colour, when defined. */
  readonly color?: string;
}

/** The ontology: every Linguist language. */
export const LANGUAGES: readonly LanguageEntry[] = [
  { name: "1C Enterprise", type: "programming", slug: "1c-enterprise", color: "#814CCC" },
  { name: "2-Dimensional Array", type: "data", slug: "2-dimensional-array", color: "#38761D" },
  { name: "4D", type: "programming", slug: "4d", color: "#004289" },
  { name: "ABAP", type: "programming", slug: "abap", color: "#E8274B" },
  { name: "ABAP CDS", type: "programming", slug: "abap-cds", color: "#555e25" },
  { name: "ABNF", type: "data", slug: "abnf" },
  { name: "AGS Script", type: "programming", slug: "ags-script", color: "#B9D9FF" },
  { name: "AIDL", type: "programming", slug: "aidl", color: "#34EB6B" },
  { name: "AL", type: "programming", slug: "al", color: "#3AA2B5" },
  { name: "ALGOL", type: "programming", slug: "algol", color: "#D1E0DB" },
  { name: "AMPL", type: "programming", slug: "ampl", color: "#E6EFBB" },
  { name: "ANTLR", type: "programming", slug: "antlr", color: "#9DC3FF" },
  { name: "API Blueprint", type: "markup", slug: "api-blueprint", color: "#2ACCA8" },
  { name: "APL", type: "programming", slug: "apl", color: "#5A8164" },
  { name: "ASL", type: "programming", slug: "asl" },
  { name: "ASN.1", type: "data", slug: "asn-1" },
  { name: "ASP.NET", type: "programming", slug: "asp-net", color: "#9400ff" },
  { name: "ATS", type: "programming", slug: "ats", color: "#1ac620" },
  { name: "ActionScript", type: "programming", slug: "actionscript", color: "#882B0F" },
  { name: "Ada", type: "programming", slug: "ada", color: "#02f88c" },
  { name: "Adblock Filter List", type: "data", slug: "adblock-filter-list", color: "#800000" },
  { name: "Adobe Font Metrics", type: "data", slug: "adobe-font-metrics", color: "#fa0f00" },
  { name: "Agda", type: "programming", slug: "agda", color: "#315665" },
  { name: "Aiken", type: "programming", slug: "aiken", color: "#640ff8" },
  { name: "Alloy", type: "programming", slug: "alloy", color: "#64C800" },
  { name: "Alpine Abuild", type: "programming", slug: "alpine-abuild", color: "#0D597F" },
  { name: "Altium Designer", type: "data", slug: "altium-designer", color: "#A89663" },
  { name: "AngelScript", type: "programming", slug: "angelscript", color: "#C7D7DC" },
  { name: "Answer Set Programming", type: "programming", slug: "answer-set-programming", color: "#A9CC29" },
  { name: "Ant Build System", type: "data", slug: "ant-build-system", color: "#A9157E" },
  { name: "Antlers", type: "markup", slug: "antlers", color: "#ff269e" },
  { name: "ApacheConf", type: "data", slug: "apacheconf", color: "#d12127" },
  { name: "Apex", type: "programming", slug: "apex", color: "#1797c0" },
  { name: "Apollo Guidance Computer", type: "programming", slug: "apollo-guidance-computer", color: "#0B3D91" },
  { name: "AppleScript", type: "programming", slug: "applescript", color: "#101F1F" },
  { name: "Arc", type: "programming", slug: "arc", color: "#aa2afe" },
  { name: "AsciiDoc", type: "prose", slug: "asciidoc", color: "#73a0c5" },
  { name: "AspectJ", type: "programming", slug: "aspectj", color: "#a957b0" },
  { name: "Assembly", type: "programming", slug: "assembly", color: "#6E4C13" },
  { name: "Astro", type: "markup", slug: "astro", color: "#ff5a03" },
  { name: "Asymptote", type: "programming", slug: "asymptote", color: "#ff0000" },
  { name: "Augeas", type: "programming", slug: "augeas", color: "#9CC134" },
  { name: "AutoHotkey", type: "programming", slug: "autohotkey", color: "#6594b9" },
  { name: "AutoIt", type: "programming", slug: "autoit", color: "#1C3552" },
  { name: "Avro IDL", type: "data", slug: "avro-idl", color: "#0040FF" },
  { name: "Awk", type: "programming", slug: "awk", color: "#c30e9b" },
  { name: "B (Formal Method)", type: "programming", slug: "b-formal-method", color: "#8aa8c5" },
  { name: "B4X", type: "programming", slug: "b4x", color: "#00e4ff" },
  { name: "BAML", type: "programming", slug: "baml", color: "#a855f7" },
  { name: "BASIC", type: "programming", slug: "basic", color: "#ff0000" },
  { name: "BQN", type: "programming", slug: "bqn", color: "#2b7067" },
  { name: "Ballerina", type: "programming", slug: "ballerina", color: "#FF5000" },
  { name: "Batchfile", type: "programming", slug: "batchfile", color: "#C1F12E" },
  { name: "Beef", type: "programming", slug: "beef", color: "#a52f4e" },
  { name: "Befunge", type: "programming", slug: "befunge" },
  { name: "Berry", type: "programming", slug: "berry", color: "#15A13C" },
  { name: "BibTeX", type: "markup", slug: "bibtex", color: "#778899" },
  { name: "BibTeX Style", type: "programming", slug: "bibtex-style" },
  { name: "Bicep", type: "programming", slug: "bicep", color: "#519aba" },
  { name: "Bikeshed", type: "markup", slug: "bikeshed", color: "#5562ac" },
  { name: "Bison", type: "programming", slug: "bison", color: "#6A463F" },
  { name: "BitBake", type: "programming", slug: "bitbake", color: "#00bce4" },
  { name: "Blade", type: "markup", slug: "blade", color: "#f7523f" },
  { name: "BlitzBasic", type: "programming", slug: "blitzbasic", color: "#00FFAE" },
  { name: "BlitzMax", type: "programming", slug: "blitzmax", color: "#cd6400" },
  { name: "Blueprint", type: "markup", slug: "blueprint", color: "#3584E4" },
  { name: "Bluespec", type: "programming", slug: "bluespec", color: "#12223c" },
  { name: "Bluespec BH", type: "programming", slug: "bluespec-bh", color: "#12223c" },
  { name: "Boo", type: "programming", slug: "boo", color: "#d4bec1" },
  { name: "Boogie", type: "programming", slug: "boogie", color: "#c80fa0" },
  { name: "Brainfuck", type: "programming", slug: "brainfuck", color: "#2F2530" },
  { name: "BrighterScript", type: "programming", slug: "brighterscript", color: "#66AABB" },
  { name: "Brightscript", type: "programming", slug: "brightscript", color: "#662D91" },
  { name: "Browserslist", type: "data", slug: "browserslist", color: "#ffd539" },
  { name: "Bru", type: "markup", slug: "bru", color: "#F4AA41" },
  { name: "BuildStream", type: "data", slug: "buildstream", color: "#006bff" },
  { name: "C", type: "programming", slug: "c", color: "#555555" },
  { name: "C#", type: "programming", slug: "csharp", color: "#7355dd" },
  { name: "C++", type: "programming", slug: "cpp", color: "#f34b7d" },
  { name: "C-ObjDump", type: "data", slug: "c-objdump" },
  { name: "C2hs Haskell", type: "programming", slug: "c2hs-haskell" },
  { name: "C3", type: "programming", slug: "c3", color: "#2563eb" },
  { name: "CAP CDS", type: "programming", slug: "cap-cds", color: "#0092d1" },
  { name: "CIL", type: "data", slug: "cil" },
  { name: "CLIPS", type: "programming", slug: "clips", color: "#00A300" },
  { name: "CMake", type: "programming", slug: "cmake", color: "#DA3434" },
  { name: "COBOL", type: "programming", slug: "cobol" },
  { name: "CODEOWNERS", type: "data", slug: "codeowners" },
  { name: "COLLADA", type: "data", slug: "collada", color: "#F1A42B" },
  { name: "CQL", type: "programming", slug: "cql", color: "#006091" },
  { name: "CSON", type: "data", slug: "cson", color: "#244776" },
  { name: "CSS", type: "markup", slug: "css", color: "#663399" },
  { name: "CSV", type: "data", slug: "csv", color: "#237346" },
  { name: "CUE", type: "programming", slug: "cue", color: "#5886E1" },
  { name: "CWeb", type: "programming", slug: "cweb", color: "#00007a" },
  { name: "Cabal Config", type: "data", slug: "cabal-config", color: "#483465" },
  { name: "Caddyfile", type: "data", slug: "caddyfile", color: "#22b638" },
  { name: "Cadence", type: "programming", slug: "cadence", color: "#00ef8b" },
  { name: "Cairo", type: "programming", slug: "cairo", color: "#ff4a48" },
  { name: "Cairo Zero", type: "programming", slug: "cairo-zero", color: "#ff4a48" },
  { name: "CameLIGO", type: "programming", slug: "cameligo", color: "#3be133" },
  { name: "Cangjie", type: "programming", slug: "cangjie", color: "#00868B" },
  { name: "Cap'n Proto", type: "programming", slug: "cap-n-proto", color: "#c42727" },
  { name: "Carbon", type: "programming", slug: "carbon", color: "#222222" },
  { name: "CartoCSS", type: "programming", slug: "cartocss" },
  { name: "Ceylon", type: "programming", slug: "ceylon", color: "#dfa535" },
  { name: "Chapel", type: "programming", slug: "chapel", color: "#8dc63f" },
  { name: "Charity", type: "programming", slug: "charity" },
  { name: "Checksums", type: "data", slug: "checksums" },
  { name: "ChucK", type: "programming", slug: "chuck", color: "#3f8000" },
  { name: "Circom", type: "programming", slug: "circom", color: "#707575" },
  { name: "Cirru", type: "programming", slug: "cirru", color: "#ccccff" },
  { name: "Clarion", type: "programming", slug: "clarion", color: "#db901e" },
  { name: "Clarity", type: "programming", slug: "clarity", color: "#5546ff" },
  { name: "Classic ASP", type: "programming", slug: "classic-asp", color: "#6a40fd" },
  { name: "Clean", type: "programming", slug: "clean", color: "#3F85AF" },
  { name: "Click", type: "programming", slug: "click", color: "#E4E6F3" },
  { name: "Clojure", type: "programming", slug: "clojure", color: "#db5855" },
  { name: "Closure Templates", type: "markup", slug: "closure-templates", color: "#0d948f" },
  { name: "Cloud Firestore Security Rules", type: "data", slug: "cloud-firestore-security-rules", color: "#FFA000" },
  { name: "Clue", type: "programming", slug: "clue", color: "#0009b5" },
  { name: "CoNLL-U", type: "data", slug: "conll-u" },
  { name: "CodeQL", type: "programming", slug: "codeql", color: "#140f46" },
  { name: "CoffeeScript", type: "programming", slug: "coffeescript", color: "#244776" },
  { name: "ColdFusion", type: "programming", slug: "coldfusion", color: "#ed2cd6" },
  { name: "ColdFusion CFC", type: "programming", slug: "coldfusion-cfc", color: "#ed2cd6" },
  { name: "Common Lisp", type: "programming", slug: "common-lisp", color: "#3fb68b" },
  { name: "Common Workflow Language", type: "programming", slug: "common-workflow-language", color: "#B5314C" },
  { name: "Component Pascal", type: "programming", slug: "component-pascal", color: "#B0CE4E" },
  { name: "Cooklang", type: "markup", slug: "cooklang", color: "#E15A29" },
  { name: "Cool", type: "programming", slug: "cool" },
  { name: "Cpp-ObjDump", type: "data", slug: "cpp-objdump" },
  { name: "Creole", type: "prose", slug: "creole" },
  { name: "Crystal", type: "programming", slug: "crystal", color: "#000100" },
  { name: "Csound", type: "programming", slug: "csound", color: "#1a1a1a" },
  { name: "Csound Document", type: "programming", slug: "csound-document", color: "#1a1a1a" },
  { name: "Csound Score", type: "programming", slug: "csound-score", color: "#1a1a1a" },
  { name: "Cuda", type: "programming", slug: "cuda", color: "#3A4E3A" },
  { name: "Cue Sheet", type: "data", slug: "cue-sheet" },
  { name: "Curry", type: "programming", slug: "curry", color: "#531242" },
  { name: "Cycript", type: "programming", slug: "cycript" },
  { name: "Cylc", type: "data", slug: "cylc", color: "#00b3fd" },
  { name: "Cypher", type: "programming", slug: "cypher", color: "#34c0eb" },
  { name: "Cython", type: "programming", slug: "cython", color: "#fedf5b" },
  { name: "D", type: "programming", slug: "d", color: "#ba595e" },
  { name: "D-ObjDump", type: "data", slug: "d-objdump" },
  { name: "D2", type: "markup", slug: "d2", color: "#526ee8" },
  { name: "DIGITAL Command Language", type: "programming", slug: "digital-command-language" },
  { name: "DM", type: "programming", slug: "dm", color: "#447265" },
  { name: "DNS Zone", type: "data", slug: "dns-zone" },
  { name: "DTrace", type: "programming", slug: "dtrace" },
  { name: "Dafny", type: "programming", slug: "dafny", color: "#FFEC25" },
  { name: "Darcs Patch", type: "data", slug: "darcs-patch", color: "#8eff23" },
  { name: "Dart", type: "programming", slug: "dart", color: "#00B4AB" },
  { name: "Daslang", type: "programming", slug: "daslang", color: "#d3d3d3" },
  { name: "DataWeave", type: "programming", slug: "dataweave", color: "#003a52" },
  { name: "Debian Package Control File", type: "data", slug: "debian-package-control-file", color: "#D70751" },
  { name: "DenizenScript", type: "programming", slug: "denizenscript", color: "#FBEE96" },
  { name: "Dhall", type: "programming", slug: "dhall", color: "#dfafff" },
  { name: "Diff", type: "data", slug: "diff" },
  { name: "DirectX 3D File", type: "data", slug: "directx-3d-file", color: "#aace60" },
  { name: "Dockerfile", type: "programming", slug: "dockerfile", color: "#384d54" },
  { name: "Dogescript", type: "programming", slug: "dogescript", color: "#cca760" },
  { name: "Dotenv", type: "data", slug: "dotenv", color: "#e5d559" },
  { name: "Dune", type: "programming", slug: "dune", color: "#89421e" },
  { name: "Dylan", type: "programming", slug: "dylan", color: "#6c616e" },
  { name: "E", type: "programming", slug: "e", color: "#ccce35" },
  { name: "E-mail", type: "data", slug: "e-mail" },
  { name: "EBNF", type: "data", slug: "ebnf" },
  { name: "ECL", type: "programming", slug: "ecl", color: "#8a1267" },
  { name: "ECLiPSe", type: "programming", slug: "eclipse", color: "#001d9d" },
  { name: "EJS", type: "markup", slug: "ejs", color: "#a91e50" },
  { name: "EQ", type: "programming", slug: "eq", color: "#a78649" },
  { name: "Eagle", type: "data", slug: "eagle" },
  { name: "Earthly", type: "programming", slug: "earthly", color: "#2af0ff" },
  { name: "Easybuild", type: "data", slug: "easybuild", color: "#069406" },
  { name: "Ecere Projects", type: "data", slug: "ecere-projects", color: "#913960" },
  { name: "Ecmarkup", type: "markup", slug: "ecmarkup", color: "#eb8131" },
  { name: "Edge", type: "markup", slug: "edge", color: "#0dffe0" },
  { name: "EdgeQL", type: "programming", slug: "edgeql", color: "#31A7FF" },
  { name: "EditorConfig", type: "data", slug: "editorconfig", color: "#fff1f2" },
  { name: "Edje Data Collection", type: "data", slug: "edje-data-collection" },
  { name: "Eiffel", type: "programming", slug: "eiffel", color: "#4d6977" },
  { name: "Elixir", type: "programming", slug: "elixir", color: "#6e4a7e" },
  { name: "Elm", type: "programming", slug: "elm", color: "#60B5CC" },
  { name: "Elvish", type: "programming", slug: "elvish", color: "#55BB55" },
  { name: "Elvish Transcript", type: "programming", slug: "elvish-transcript", color: "#55BB55" },
  { name: "Emacs Lisp", type: "programming", slug: "emacs-lisp", color: "#c065db" },
  { name: "EmberScript", type: "programming", slug: "emberscript", color: "#FFF4F3" },
  { name: "Erlang", type: "programming", slug: "erlang", color: "#B83998" },
  { name: "Euphoria", type: "programming", slug: "euphoria", color: "#FF790B" },
  { name: "F#", type: "programming", slug: "fsharp", color: "#b845fc" },
  { name: "F*", type: "programming", slug: "f", color: "#572e30" },
  { name: "FIGlet Font", type: "data", slug: "figlet-font", color: "#FFDDBB" },
  { name: "FIRRTL", type: "programming", slug: "firrtl", color: "#2f632f" },
  { name: "FLUX", type: "programming", slug: "flux", color: "#88ccff" },
  { name: "Factor", type: "programming", slug: "factor", color: "#636746" },
  { name: "Fancy", type: "programming", slug: "fancy", color: "#7b9db4" },
  { name: "Fantom", type: "programming", slug: "fantom", color: "#14253c" },
  { name: "Faust", type: "programming", slug: "faust", color: "#c37240" },
  { name: "Fennel", type: "programming", slug: "fennel", color: "#fff3d7" },
  { name: "Filebench WML", type: "programming", slug: "filebench-wml", color: "#F6B900" },
  { name: "Filterscript", type: "programming", slug: "filterscript" },
  { name: "FlatBuffers", type: "data", slug: "flatbuffers", color: "#ed284a" },
  { name: "Flix", type: "programming", slug: "flix", color: "#d44a45" },
  { name: "Fluent", type: "programming", slug: "fluent", color: "#ffcc33" },
  { name: "Formatted", type: "data", slug: "formatted" },
  { name: "Forth", type: "programming", slug: "forth", color: "#341708" },
  { name: "Fortran", type: "programming", slug: "fortran", color: "#4d41b1" },
  { name: "Fortran Free Form", type: "programming", slug: "fortran-free-form", color: "#4d41b1" },
  { name: "FreeBASIC", type: "programming", slug: "freebasic", color: "#141AC9" },
  { name: "FreeMarker", type: "programming", slug: "freemarker", color: "#0050b2" },
  { name: "Frege", type: "programming", slug: "frege", color: "#00cafe" },
  { name: "Futhark", type: "programming", slug: "futhark", color: "#5f021f" },
  { name: "G-code", type: "programming", slug: "g-code", color: "#D08CF2" },
  { name: "GAML", type: "programming", slug: "gaml", color: "#FFC766" },
  { name: "GAMS", type: "programming", slug: "gams", color: "#f49a22" },
  { name: "GAP", type: "programming", slug: "gap", color: "#0000cc" },
  { name: "GCC Machine Description", type: "programming", slug: "gcc-machine-description", color: "#FFCFAB" },
  { name: "GDB", type: "programming", slug: "gdb" },
  { name: "GDScript", type: "programming", slug: "gdscript", color: "#355570" },
  { name: "GDShader", type: "programming", slug: "gdshader", color: "#478CBF" },
  { name: "GEDCOM", type: "data", slug: "gedcom", color: "#003058" },
  { name: "GLSL", type: "programming", slug: "glsl", color: "#5686a5" },
  { name: "GN", type: "data", slug: "gn" },
  { name: "GSC", type: "programming", slug: "gsc", color: "#FF6800" },
  { name: "Game Maker Language", type: "programming", slug: "game-maker-language", color: "#71b417" },
  { name: "Gemfile.lock", type: "data", slug: "gemfile-lock", color: "#701516" },
  { name: "Gemini", type: "prose", slug: "gemini", color: "#ff6900" },
  { name: "Genero 4gl", type: "programming", slug: "genero-4gl", color: "#63408e" },
  { name: "Genero per", type: "markup", slug: "genero-per", color: "#d8df39" },
  { name: "Genie", type: "programming", slug: "genie", color: "#fb855d" },
  { name: "Genshi", type: "programming", slug: "genshi", color: "#951531" },
  { name: "Gentoo Ebuild", type: "programming", slug: "gentoo-ebuild", color: "#9400ff" },
  { name: "Gentoo Eclass", type: "programming", slug: "gentoo-eclass", color: "#9400ff" },
  { name: "Gerber Image", type: "data", slug: "gerber-image", color: "#d20b00" },
  { name: "Gettext Catalog", type: "prose", slug: "gettext-catalog" },
  { name: "Gherkin", type: "programming", slug: "gherkin", color: "#5B2063" },
  { name: "Git Attributes", type: "data", slug: "git-attributes", color: "#F44D27" },
  { name: "Git Commit", type: "data", slug: "git-commit", color: "#F44D27" },
  { name: "Git Config", type: "data", slug: "git-config", color: "#F44D27" },
  { name: "Git Revision List", type: "data", slug: "git-revision-list", color: "#F44D27" },
  { name: "Gleam", type: "programming", slug: "gleam", color: "#ffaff3" },
  { name: "Glimmer JS", type: "programming", slug: "glimmer-js", color: "#F5835F" },
  { name: "Glimmer TS", type: "programming", slug: "glimmer-ts", color: "#3178c6" },
  { name: "Glyph", type: "programming", slug: "glyph", color: "#c1ac7f" },
  { name: "Glyph Bitmap Distribution Format", type: "data", slug: "glyph-bitmap-distribution-format" },
  { name: "Gnuplot", type: "programming", slug: "gnuplot", color: "#f0a9f0" },
  { name: "Go", type: "programming", slug: "go", color: "#00ADD8" },
  { name: "Go Checksums", type: "data", slug: "go-checksums", color: "#00ADD8" },
  { name: "Go Module", type: "data", slug: "go-module", color: "#00ADD8" },
  { name: "Go Template", type: "markup", slug: "go-template", color: "#00ADD8" },
  { name: "Go Workspace", type: "data", slug: "go-workspace", color: "#00ADD8" },
  { name: "Godot Resource", type: "data", slug: "godot-resource", color: "#355570" },
  { name: "Golo", type: "programming", slug: "golo", color: "#88562A" },
  { name: "Gosu", type: "programming", slug: "gosu", color: "#82937f" },
  { name: "Grace", type: "programming", slug: "grace", color: "#615f8b" },
  { name: "Gradle", type: "data", slug: "gradle", color: "#02303a" },
  { name: "Gradle Kotlin DSL", type: "data", slug: "gradle-kotlin-dsl", color: "#02303a" },
  { name: "Grammatical Framework", type: "programming", slug: "grammatical-framework", color: "#ff0000" },
  { name: "Graph Modeling Language", type: "data", slug: "graph-modeling-language" },
  { name: "GraphQL", type: "data", slug: "graphql", color: "#e10098" },
  { name: "Graphviz (DOT)", type: "data", slug: "graphviz-dot", color: "#2596be" },
  { name: "Groovy", type: "programming", slug: "groovy", color: "#4298b8" },
  { name: "Groovy Server Pages", type: "programming", slug: "groovy-server-pages", color: "#4298b8" },
  { name: "GtkRC", type: "data", slug: "gtkrc", color: "#7fe719" },
  { name: "HAProxy", type: "data", slug: "haproxy", color: "#106da9" },
  { name: "HCL", type: "programming", slug: "hcl", color: "#844FBA" },
  { name: "HIP", type: "programming", slug: "hip", color: "#4F3A4F" },
  { name: "HLSL", type: "programming", slug: "hlsl", color: "#aace60" },
  { name: "HOCON", type: "data", slug: "hocon", color: "#9ff8ee" },
  { name: "HTML", type: "markup", slug: "html", color: "#e34c26" },
  { name: "HTML+ECR", type: "markup", slug: "htmlpecr", color: "#2e1052" },
  { name: "HTML+EEX", type: "markup", slug: "htmlpeex", color: "#6e4a7e" },
  { name: "HTML+ERB", type: "markup", slug: "htmlperb", color: "#701516" },
  { name: "HTML+PHP", type: "markup", slug: "htmlpphp", color: "#4f5d95" },
  { name: "HTML+Razor", type: "markup", slug: "htmlprazor", color: "#512be4" },
  { name: "HTTP", type: "data", slug: "http", color: "#005C9C" },
  { name: "HXML", type: "data", slug: "hxml", color: "#f68712" },
  { name: "Hack", type: "programming", slug: "hack", color: "#878787" },
  { name: "Haml", type: "markup", slug: "haml", color: "#ece2a9" },
  { name: "Handlebars", type: "markup", slug: "handlebars", color: "#f7931e" },
  { name: "Harbour", type: "programming", slug: "harbour", color: "#0e60e3" },
  { name: "Hare", type: "programming", slug: "hare", color: "#9d7424" },
  { name: "Haskell", type: "programming", slug: "haskell", color: "#5e5086" },
  { name: "Haxe", type: "programming", slug: "haxe", color: "#df7900" },
  { name: "HiveQL", type: "programming", slug: "hiveql", color: "#dce200" },
  { name: "HolyC", type: "programming", slug: "holyc", color: "#ffefaf" },
  { name: "Hosts File", type: "data", slug: "hosts-file", color: "#308888" },
  { name: "Hurl", type: "programming", slug: "hurl", color: "#FF0288" },
  { name: "Hy", type: "programming", slug: "hy", color: "#7790B2" },
  { name: "HyPhy", type: "programming", slug: "hyphy" },
  { name: "IDL", type: "programming", slug: "idl", color: "#a3522f" },
  { name: "IGOR Pro", type: "programming", slug: "igor-pro", color: "#0000cc" },
  { name: "IL Assembly", type: "programming", slug: "il-assembly", color: "#512BD4" },
  { name: "INI", type: "data", slug: "ini", color: "#d1dbe0" },
  { name: "IRC log", type: "data", slug: "irc-log" },
  { name: "ISPC", type: "programming", slug: "ispc", color: "#2D68B1" },
  { name: "Idris", type: "programming", slug: "idris", color: "#b30000" },
  { name: "Ignore List", type: "data", slug: "ignore-list", color: "#000000" },
  { name: "ImageJ Macro", type: "programming", slug: "imagej-macro", color: "#99AAFF" },
  { name: "Imba", type: "programming", slug: "imba", color: "#16cec6" },
  { name: "Inform 7", type: "programming", slug: "inform-7" },
  { name: "Ink", type: "programming", slug: "ink" },
  { name: "Inno Setup", type: "programming", slug: "inno-setup", color: "#264b99" },
  { name: "Io", type: "programming", slug: "io", color: "#a9188d" },
  { name: "Ioke", type: "programming", slug: "ioke", color: "#078193" },
  { name: "Isabelle", type: "programming", slug: "isabelle", color: "#FEFE00" },
  { name: "Isabelle ROOT", type: "programming", slug: "isabelle-root", color: "#FEFE00" },
  { name: "J", type: "programming", slug: "j", color: "#9EEDFF" },
  { name: "JAR Manifest", type: "data", slug: "jar-manifest", color: "#b07219" },
  { name: "JCL", type: "programming", slug: "jcl", color: "#d90e09" },
  { name: "JFlex", type: "programming", slug: "jflex", color: "#DBCA00" },
  { name: "JSON", type: "data", slug: "json", color: "#292929" },
  { name: "JSON with Comments", type: "data", slug: "json-with-comments", color: "#292929" },
  { name: "JSON5", type: "data", slug: "json5", color: "#267CB9" },
  { name: "JSONLD", type: "data", slug: "jsonld", color: "#0c479c" },
  { name: "JSONiq", type: "programming", slug: "jsoniq", color: "#40d47e" },
  { name: "Jac", type: "programming", slug: "jac", color: "#FC792D" },
  { name: "Jai", type: "programming", slug: "jai", color: "#ab8b4b" },
  { name: "Janet", type: "programming", slug: "janet", color: "#0886a5" },
  { name: "Jasmin", type: "programming", slug: "jasmin", color: "#d03600" },
  { name: "Java", type: "programming", slug: "java", color: "#b07219" },
  { name: "Java Properties", type: "data", slug: "java-properties", color: "#2A6277" },
  { name: "Java Server Pages", type: "programming", slug: "java-server-pages", color: "#2A6277" },
  { name: "Java Template Engine", type: "programming", slug: "java-template-engine", color: "#2A6277" },
  { name: "JavaScript", type: "programming", slug: "javascript", color: "#f1e05a" },
  { name: "JavaScript+ERB", type: "programming", slug: "javascriptperb", color: "#f1e05a" },
  { name: "Jest Snapshot", type: "data", slug: "jest-snapshot", color: "#15c213" },
  { name: "JetBrains MPS", type: "programming", slug: "jetbrains-mps", color: "#21D789" },
  { name: "Jinja", type: "markup", slug: "jinja", color: "#a52a22" },
  { name: "Jison", type: "programming", slug: "jison", color: "#56b3cb" },
  { name: "Jison Lex", type: "programming", slug: "jison-lex", color: "#56b3cb" },
  { name: "Jolie", type: "programming", slug: "jolie", color: "#843179" },
  { name: "Jsonnet", type: "programming", slug: "jsonnet", color: "#0064bd" },
  { name: "Julia", type: "programming", slug: "julia", color: "#a270ba" },
  { name: "Julia REPL", type: "programming", slug: "julia-repl", color: "#a270ba" },
  { name: "Jupyter Notebook", type: "markup", slug: "jupyter-notebook", color: "#DA5B0B" },
  { name: "Just", type: "programming", slug: "just", color: "#384d54" },
  { name: "KCL", type: "programming", slug: "kcl", color: "#7ABABF" },
  { name: "KDL", type: "data", slug: "kdl", color: "#ffb3b3" },
  { name: "KFramework", type: "programming", slug: "kframework", color: "#4195c5" },
  { name: "KRL", type: "programming", slug: "krl", color: "#28430A" },
  { name: "Kaitai Struct", type: "programming", slug: "kaitai-struct", color: "#773b37" },
  { name: "KakouneScript", type: "programming", slug: "kakounescript", color: "#6f8042" },
  { name: "KerboScript", type: "programming", slug: "kerboscript", color: "#41adf0" },
  { name: "KiCad Layout", type: "data", slug: "kicad-layout", color: "#2f4aab" },
  { name: "KiCad Legacy Layout", type: "data", slug: "kicad-legacy-layout", color: "#2f4aab" },
  { name: "KiCad Schematic", type: "data", slug: "kicad-schematic", color: "#2f4aab" },
  { name: "Kickstart", type: "data", slug: "kickstart" },
  { name: "Kit", type: "markup", slug: "kit" },
  { name: "KoLmafia ASH", type: "programming", slug: "kolmafia-ash", color: "#B9D9B9" },
  { name: "Koka", type: "programming", slug: "koka", color: "#215166" },
  { name: "Kotlin", type: "programming", slug: "kotlin", color: "#A97BFF" },
  { name: "Kusto", type: "data", slug: "kusto" },
  { name: "LFE", type: "programming", slug: "lfe", color: "#4C3023" },
  { name: "LLVM", type: "programming", slug: "llvm", color: "#185619" },
  { name: "LOLCODE", type: "programming", slug: "lolcode", color: "#cc9900" },
  { name: "LSL", type: "programming", slug: "lsl", color: "#3d9970" },
  { name: "LTspice Symbol", type: "data", slug: "ltspice-symbol" },
  { name: "LabVIEW", type: "programming", slug: "labview", color: "#fede06" },
  { name: "Lambdapi", type: "programming", slug: "lambdapi", color: "#8027a3" },
  { name: "Langium", type: "programming", slug: "langium", color: "#2c8c87" },
  { name: "Lark", type: "data", slug: "lark", color: "#2980B9" },
  { name: "Lasso", type: "programming", slug: "lasso", color: "#999999" },
  { name: "Latte", type: "markup", slug: "latte", color: "#f2a542" },
  { name: "Lean", type: "programming", slug: "lean" },
  { name: "Lean 4", type: "programming", slug: "lean-4" },
  { name: "Leo", type: "programming", slug: "leo", color: "#C4FFC2" },
  { name: "Less", type: "markup", slug: "less", color: "#1d365d" },
  { name: "Lex", type: "programming", slug: "lex", color: "#DBCA00" },
  { name: "LigoLANG", type: "programming", slug: "ligolang", color: "#0e74ff" },
  { name: "LilyPond", type: "programming", slug: "lilypond", color: "#9ccc7c" },
  { name: "Limbo", type: "programming", slug: "limbo" },
  { name: "Linear Programming", type: "programming", slug: "linear-programming" },
  { name: "Linker Script", type: "programming", slug: "linker-script" },
  { name: "Linux Kernel Module", type: "data", slug: "linux-kernel-module" },
  { name: "Liquid", type: "markup", slug: "liquid", color: "#67b8de" },
  { name: "Liquidsoap", type: "programming", slug: "liquidsoap", color: "#990066" },
  { name: "Literate Agda", type: "programming", slug: "literate-agda", color: "#315665" },
  { name: "Literate CoffeeScript", type: "programming", slug: "literate-coffeescript", color: "#244776" },
  { name: "Literate Haskell", type: "programming", slug: "literate-haskell", color: "#5e5086" },
  { name: "LiveCode Script", type: "programming", slug: "livecode-script", color: "#0c5ba5" },
  { name: "LiveScript", type: "programming", slug: "livescript", color: "#499886" },
  { name: "Logos", type: "programming", slug: "logos" },
  { name: "Logtalk", type: "programming", slug: "logtalk", color: "#295b9a" },
  { name: "LookML", type: "programming", slug: "lookml", color: "#652B81" },
  { name: "LoomScript", type: "programming", slug: "loomscript" },
  { name: "Lua", type: "programming", slug: "lua", color: "#000080" },
  { name: "Luau", type: "programming", slug: "luau", color: "#00A2FF" },
  { name: "M", type: "programming", slug: "m" },
  { name: "M3U", type: "data", slug: "m3u", color: "#179C7D" },
  { name: "M4", type: "programming", slug: "m4" },
  { name: "M4Sugar", type: "programming", slug: "m4sugar" },
  { name: "MATLAB", type: "programming", slug: "matlab", color: "#e16737" },
  { name: "MAXScript", type: "programming", slug: "maxscript", color: "#00a6a6" },
  { name: "MDX", type: "markup", slug: "mdx", color: "#fcb32c" },
  { name: "MLIR", type: "programming", slug: "mlir", color: "#5EC8DB" },
  { name: "MQL4", type: "programming", slug: "mql4", color: "#62A8D6" },
  { name: "MQL5", type: "programming", slug: "mql5", color: "#4A76B8" },
  { name: "MTML", type: "markup", slug: "mtml", color: "#b7e1f4" },
  { name: "MUF", type: "programming", slug: "muf" },
  { name: "Macaulay2", type: "programming", slug: "macaulay2", color: "#d8ffff" },
  { name: "Makefile", type: "programming", slug: "makefile", color: "#427819" },
  { name: "Mako", type: "programming", slug: "mako", color: "#7e858d" },
  { name: "Markdown", type: "prose", slug: "markdown", color: "#083fa1" },
  { name: "Marko", type: "markup", slug: "marko", color: "#42bff2" },
  { name: "Mask", type: "markup", slug: "mask", color: "#f97732" },
  { name: "Mathematical Programming System", type: "programming", slug: "mathematical-programming-system", color: "#0530ad" },
  { name: "Maven POM", type: "data", slug: "maven-pom" },
  { name: "Max", type: "programming", slug: "max", color: "#c4a79c" },
  { name: "MeTTa", type: "programming", slug: "metta", color: "#6a5acd" },
  { name: "Mercury", type: "programming", slug: "mercury", color: "#ff2b2b" },
  { name: "Mermaid", type: "markup", slug: "mermaid", color: "#ff3670" },
  { name: "Meson", type: "programming", slug: "meson", color: "#007800" },
  { name: "Metal", type: "programming", slug: "metal", color: "#8f14e9" },
  { name: "Microsoft Developer Studio Project", type: "data", slug: "microsoft-developer-studio-project" },
  { name: "Microsoft Visual Studio Solution", type: "data", slug: "microsoft-visual-studio-solution" },
  { name: "MiniD", type: "programming", slug: "minid" },
  { name: "MiniYAML", type: "data", slug: "miniyaml", color: "#ff1111" },
  { name: "MiniZinc", type: "programming", slug: "minizinc", color: "#06a9e6" },
  { name: "MiniZinc Data", type: "data", slug: "minizinc-data" },
  { name: "Mint", type: "programming", slug: "mint", color: "#02b046" },
  { name: "Mirah", type: "programming", slug: "mirah", color: "#c7a938" },
  { name: "Modelica", type: "programming", slug: "modelica", color: "#de1d31" },
  { name: "Modula-2", type: "programming", slug: "modula-2", color: "#10253f" },
  { name: "Modula-3", type: "programming", slug: "modula-3", color: "#223388" },
  { name: "Module Management System", type: "programming", slug: "module-management-system" },
  { name: "Mojo", type: "programming", slug: "mojo", color: "#ff4c1f" },
  { name: "Monkey", type: "programming", slug: "monkey" },
  { name: "Monkey C", type: "programming", slug: "monkey-c", color: "#8D6747" },
  { name: "Moocode", type: "programming", slug: "moocode" },
  { name: "MoonBit", type: "programming", slug: "moonbit", color: "#b92381" },
  { name: "MoonScript", type: "programming", slug: "moonscript", color: "#ff4585" },
  { name: "Motoko", type: "programming", slug: "motoko", color: "#fbb03b" },
  { name: "Motorola 68K Assembly", type: "programming", slug: "motorola-68k-assembly", color: "#005daa" },
  { name: "Move", type: "programming", slug: "move", color: "#4a137a" },
  { name: "Muse", type: "prose", slug: "muse" },
  { name: "Mustache", type: "markup", slug: "mustache", color: "#724b3b" },
  { name: "Myghty", type: "programming", slug: "myghty" },
  { name: "NASL", type: "programming", slug: "nasl" },
  { name: "NCL", type: "programming", slug: "ncl", color: "#28431f" },
  { name: "NEON", type: "data", slug: "neon" },
  { name: "NL", type: "data", slug: "nl" },
  { name: "NMODL", type: "programming", slug: "nmodl", color: "#00356B" },
  { name: "NPM Config", type: "data", slug: "npm-config", color: "#cb3837" },
  { name: "NSIS", type: "programming", slug: "nsis" },
  { name: "NWScript", type: "programming", slug: "nwscript", color: "#111522" },
  { name: "Nasal", type: "programming", slug: "nasal", color: "#1d2c4e" },
  { name: "Nearley", type: "programming", slug: "nearley", color: "#990000" },
  { name: "Nemerle", type: "programming", slug: "nemerle", color: "#3d3c6e" },
  { name: "NetLinx", type: "programming", slug: "netlinx", color: "#0aa0ff" },
  { name: "NetLinx+ERB", type: "programming", slug: "netlinxperb", color: "#747faa" },
  { name: "NetLogo", type: "programming", slug: "netlogo", color: "#ff6375" },
  { name: "NewLisp", type: "programming", slug: "newlisp", color: "#87AED7" },
  { name: "Nextflow", type: "programming", slug: "nextflow", color: "#3ac486" },
  { name: "Nginx", type: "data", slug: "nginx", color: "#009639" },
  { name: "Nickel", type: "programming", slug: "nickel", color: "#E0C3FC" },
  { name: "Nim", type: "programming", slug: "nim", color: "#ffc200" },
  { name: "Ninja", type: "data", slug: "ninja" },
  { name: "Nit", type: "programming", slug: "nit", color: "#009917" },
  { name: "Nix", type: "programming", slug: "nix", color: "#7e7eff" },
  { name: "Noir", type: "programming", slug: "noir", color: "#2f1f49" },
  { name: "Nu", type: "programming", slug: "nu", color: "#c9df40" },
  { name: "NumPy", type: "programming", slug: "numpy", color: "#9C8AF9" },
  { name: "Nunjucks", type: "markup", slug: "nunjucks", color: "#3d8137" },
  { name: "Nushell", type: "programming", slug: "nushell", color: "#4E9906" },
  { name: "OASv2-json", type: "data", slug: "oasv2-json", color: "#85ea2d" },
  { name: "OASv2-yaml", type: "data", slug: "oasv2-yaml", color: "#85ea2d" },
  { name: "OASv3-json", type: "data", slug: "oasv3-json", color: "#85ea2d" },
  { name: "OASv3-yaml", type: "data", slug: "oasv3-yaml", color: "#85ea2d" },
  { name: "OCaml", type: "programming", slug: "ocaml", color: "#ef7a08" },
  { name: "OMNeT++ MSG", type: "programming", slug: "omnetpp-msg", color: "#a0e0a0" },
  { name: "OMNeT++ NED", type: "programming", slug: "omnetpp-ned", color: "#08607c" },
  { name: "Oberon", type: "programming", slug: "oberon" },
  { name: "ObjDump", type: "data", slug: "objdump" },
  { name: "Object Data Instance Notation", type: "data", slug: "object-data-instance-notation" },
  { name: "ObjectScript", type: "programming", slug: "objectscript", color: "#424893" },
  { name: "Objective-C", type: "programming", slug: "objective-c", color: "#438eff" },
  { name: "Objective-C++", type: "programming", slug: "objective-cpp", color: "#6866fb" },
  { name: "Objective-J", type: "programming", slug: "objective-j", color: "#ff0c5a" },
  { name: "Odin", type: "programming", slug: "odin", color: "#60AFFE" },
  { name: "Omgrofl", type: "programming", slug: "omgrofl", color: "#cabbff" },
  { name: "Opa", type: "programming", slug: "opa" },
  { name: "Opal", type: "programming", slug: "opal", color: "#f7ede0" },
  { name: "Open Policy Agent", type: "programming", slug: "open-policy-agent", color: "#7d9199" },
  { name: "OpenAPI Specification v2", type: "data", slug: "openapi-specification-v2", color: "#85ea2d" },
  { name: "OpenAPI Specification v3", type: "data", slug: "openapi-specification-v3", color: "#85ea2d" },
  { name: "OpenCL", type: "programming", slug: "opencl", color: "#ed2e2d" },
  { name: "OpenEdge ABL", type: "programming", slug: "openedge-abl", color: "#5ce600" },
  { name: "OpenQASM", type: "programming", slug: "openqasm", color: "#AA70FF" },
  { name: "OpenRC runscript", type: "programming", slug: "openrc-runscript" },
  { name: "OpenSCAD", type: "programming", slug: "openscad", color: "#e5cd45" },
  { name: "OpenStep Property List", type: "data", slug: "openstep-property-list" },
  { name: "OpenType Feature File", type: "data", slug: "opentype-feature-file" },
  { name: "Option List", type: "data", slug: "option-list", color: "#476732" },
  { name: "Org", type: "prose", slug: "org", color: "#77aa99" },
  { name: "OverPy", type: "programming", slug: "overpy", color: "#78b355" },
  { name: "OverpassQL", type: "programming", slug: "overpassql", color: "#cce2aa" },
  { name: "Ox", type: "programming", slug: "ox" },
  { name: "Oxygene", type: "programming", slug: "oxygene", color: "#cdd0e3" },
  { name: "Oz", type: "programming", slug: "oz", color: "#fab738" },
  { name: "P4", type: "programming", slug: "p4", color: "#7055b5" },
  { name: "PDDL", type: "programming", slug: "pddl", color: "#0d00ff" },
  { name: "PEG.js", type: "programming", slug: "peg-js", color: "#234d6b" },
  { name: "PHP", type: "programming", slug: "php", color: "#4F5D95" },
  { name: "PLSQL", type: "programming", slug: "plsql", color: "#dad8d8" },
  { name: "PLpgSQL", type: "programming", slug: "plpgsql", color: "#336790" },
  { name: "POV-Ray SDL", type: "programming", slug: "pov-ray-sdl", color: "#6bac65" },
  { name: "Pact", type: "programming", slug: "pact", color: "#F7A8B8" },
  { name: "Pan", type: "programming", slug: "pan", color: "#cc0000" },
  { name: "Papyrus", type: "programming", slug: "papyrus", color: "#6600cc" },
  { name: "Parrot", type: "programming", slug: "parrot", color: "#f3ca0a" },
  { name: "Parrot Assembly", type: "programming", slug: "parrot-assembly" },
  { name: "Parrot Internal Representation", type: "programming", slug: "parrot-internal-representation" },
  { name: "Pascal", type: "programming", slug: "pascal", color: "#E3F171" },
  { name: "Pawn", type: "programming", slug: "pawn", color: "#dbb284" },
  { name: "Pep8", type: "programming", slug: "pep8", color: "#C76F5B" },
  { name: "Perl", type: "programming", slug: "perl", color: "#0298c3" },
  { name: "Pic", type: "markup", slug: "pic" },
  { name: "Pickle", type: "data", slug: "pickle" },
  { name: "PicoLisp", type: "programming", slug: "picolisp", color: "#6067af" },
  { name: "PigLatin", type: "programming", slug: "piglatin", color: "#fcd7de" },
  { name: "Pike", type: "programming", slug: "pike", color: "#005390" },
  { name: "Pip Requirements", type: "data", slug: "pip-requirements", color: "#FFD343" },
  { name: "Pkl", type: "programming", slug: "pkl", color: "#6b9543" },
  { name: "PlantUML", type: "data", slug: "plantuml", color: "#fbbd16" },
  { name: "Pod", type: "prose", slug: "pod" },
  { name: "Pod 6", type: "prose", slug: "pod-6" },
  { name: "PogoScript", type: "programming", slug: "pogoscript", color: "#d80074" },
  { name: "Polar", type: "programming", slug: "polar", color: "#ae81ff" },
  { name: "Pony", type: "programming", slug: "pony" },
  { name: "Portugol", type: "programming", slug: "portugol", color: "#f8bd00" },
  { name: "PostCSS", type: "markup", slug: "postcss", color: "#dc3a0c" },
  { name: "PostScript", type: "markup", slug: "postscript", color: "#da291c" },
  { name: "Power Query", type: "programming", slug: "power-query", color: "#d38e0d" },
  { name: "PowerBuilder", type: "programming", slug: "powerbuilder", color: "#8f0f8d" },
  { name: "PowerShell", type: "programming", slug: "powershell", color: "#012456" },
  { name: "Praat", type: "programming", slug: "praat", color: "#c8506d" },
  { name: "Prisma", type: "data", slug: "prisma", color: "#0c344b" },
  { name: "Pro*C", type: "programming", slug: "pro-c", color: "#bb8368" },
  { name: "Processing", type: "programming", slug: "processing", color: "#0096D8" },
  { name: "Procfile", type: "programming", slug: "procfile", color: "#3B2F63" },
  { name: "Proguard", type: "data", slug: "proguard" },
  { name: "Prolog", type: "programming", slug: "prolog", color: "#74283c" },
  { name: "Promela", type: "programming", slug: "promela", color: "#de0000" },
  { name: "Propeller Spin", type: "programming", slug: "propeller-spin", color: "#7fa2a7" },
  { name: "Protocol Buffer", type: "data", slug: "protocol-buffer" },
  { name: "Protocol Buffer Text Format", type: "data", slug: "protocol-buffer-text-format" },
  { name: "Public Key", type: "data", slug: "public-key" },
  { name: "Pug", type: "markup", slug: "pug", color: "#a86454" },
  { name: "Puppet", type: "programming", slug: "puppet", color: "#302B6D" },
  { name: "Pure Data", type: "data", slug: "pure-data" },
  { name: "PureBasic", type: "programming", slug: "purebasic", color: "#5a6986" },
  { name: "PureScript", type: "programming", slug: "purescript", color: "#1D222D" },
  { name: "Pyret", type: "programming", slug: "pyret", color: "#ee1e10" },
  { name: "Python", type: "programming", slug: "python", color: "#3572A5" },
  { name: "Python console", type: "programming", slug: "python-console", color: "#3572A5" },
  { name: "Python traceback", type: "data", slug: "python-traceback", color: "#3572A5" },
  { name: "Q#", type: "programming", slug: "qsharp", color: "#fed659" },
  { name: "QML", type: "programming", slug: "qml", color: "#44a51c" },
  { name: "QMake", type: "programming", slug: "qmake" },
  { name: "Qt Script", type: "programming", slug: "qt-script", color: "#00b841" },
  { name: "Quake", type: "programming", slug: "quake", color: "#882233" },
  { name: "QuakeC", type: "programming", slug: "quakec", color: "#975777" },
  { name: "QuickBASIC", type: "programming", slug: "quickbasic", color: "#008080" },
  { name: "Quint", type: "programming", slug: "quint", color: "#9d6ce5" },
  { name: "R", type: "programming", slug: "r", color: "#198CE7" },
  { name: "RAML", type: "markup", slug: "raml", color: "#77d9fb" },
  { name: "RAScript", type: "programming", slug: "rascript", color: "#2C97FA" },
  { name: "RBS", type: "data", slug: "rbs", color: "#701516" },
  { name: "RDoc", type: "prose", slug: "rdoc", color: "#701516" },
  { name: "REALbasic", type: "programming", slug: "realbasic" },
  { name: "REXX", type: "programming", slug: "rexx", color: "#d90e09" },
  { name: "RMarkdown", type: "prose", slug: "rmarkdown", color: "#198ce7" },
  { name: "RON", type: "data", slug: "ron", color: "#a62c00" },
  { name: "ROS Interface", type: "data", slug: "ros-interface", color: "#22314e" },
  { name: "RPC", type: "programming", slug: "rpc" },
  { name: "RPGLE", type: "programming", slug: "rpgle", color: "#2BDE21" },
  { name: "RPM Spec", type: "data", slug: "rpm-spec" },
  { name: "RUNOFF", type: "markup", slug: "runoff", color: "#665a4e" },
  { name: "Racket", type: "programming", slug: "racket", color: "#3c5caa" },
  { name: "Ragel", type: "programming", slug: "ragel", color: "#9d5200" },
  { name: "Raku", type: "programming", slug: "raku", color: "#0000fb" },
  { name: "Rascal", type: "programming", slug: "rascal", color: "#fffaa0" },
  { name: "Raw token data", type: "data", slug: "raw-token-data" },
  { name: "ReScript", type: "programming", slug: "rescript", color: "#ed5051" },
  { name: "Readline Config", type: "data", slug: "readline-config" },
  { name: "Reason", type: "programming", slug: "reason", color: "#ff5847" },
  { name: "ReasonLIGO", type: "programming", slug: "reasonligo", color: "#ff5847" },
  { name: "Rebol", type: "programming", slug: "rebol", color: "#358a5b" },
  { name: "Record Jar", type: "data", slug: "record-jar", color: "#0673ba" },
  { name: "Red", type: "programming", slug: "red", color: "#f50000" },
  { name: "Redcode", type: "programming", slug: "redcode" },
  { name: "Redirect Rules", type: "data", slug: "redirect-rules" },
  { name: "Redscript", type: "programming", slug: "redscript", color: "#f44336" },
  { name: "Regular Expression", type: "data", slug: "regular-expression", color: "#009a00" },
  { name: "Ren'Py", type: "programming", slug: "ren-py", color: "#ff7f7f" },
  { name: "RenderScript", type: "programming", slug: "renderscript" },
  { name: "Rez", type: "programming", slug: "rez", color: "#FFDAB3" },
  { name: "Rich Text Format", type: "markup", slug: "rich-text-format" },
  { name: "Ring", type: "programming", slug: "ring", color: "#2D54CB" },
  { name: "Riot", type: "markup", slug: "riot", color: "#A71E49" },
  { name: "RobotFramework", type: "programming", slug: "robotframework", color: "#00c0b5" },
  { name: "Robots Exclusion Rules", type: "data", slug: "robots-exclusion-rules" },
  { name: "Roc", type: "programming", slug: "roc", color: "#7c38f5" },
  { name: "Rocq Prover", type: "programming", slug: "rocq-prover", color: "#d0b68c" },
  { name: "Roff", type: "markup", slug: "roff", color: "#ecdebe" },
  { name: "Roff Manpage", type: "markup", slug: "roff-manpage", color: "#ecdebe" },
  { name: "Rouge", type: "programming", slug: "rouge", color: "#cc0088" },
  { name: "RouterOS Script", type: "programming", slug: "routeros-script", color: "#DE3941" },
  { name: "Ruby", type: "programming", slug: "ruby", color: "#701516" },
  { name: "Rust", type: "programming", slug: "rust", color: "#dea584" },
  { name: "SAS", type: "programming", slug: "sas", color: "#B34936" },
  { name: "SCSS", type: "markup", slug: "scss", color: "#c6538c" },
  { name: "SELinux Policy", type: "data", slug: "selinux-policy" },
  { name: "SMT", type: "programming", slug: "smt" },
  { name: "SPARQL", type: "data", slug: "sparql", color: "#0C4597" },
  { name: "SQF", type: "programming", slug: "sqf", color: "#3F3F3F" },
  { name: "SQL", type: "data", slug: "sql", color: "#e38c00" },
  { name: "SQLPL", type: "programming", slug: "sqlpl", color: "#e38c00" },
  { name: "SRecode Template", type: "markup", slug: "srecode-template", color: "#348a34" },
  { name: "SSH Config", type: "data", slug: "ssh-config" },
  { name: "STAR", type: "data", slug: "star" },
  { name: "STL", type: "data", slug: "stl", color: "#373b5e" },
  { name: "STON", type: "data", slug: "ston" },
  { name: "SVG", type: "data", slug: "svg", color: "#ff9900" },
  { name: "SWIG", type: "programming", slug: "swig" },
  { name: "Sage", type: "programming", slug: "sage" },
  { name: "Sail", type: "programming", slug: "sail", color: "#259dd5" },
  { name: "SaltStack", type: "programming", slug: "saltstack", color: "#646464" },
  { name: "Sass", type: "markup", slug: "sass", color: "#a53b70" },
  { name: "Scala", type: "programming", slug: "scala", color: "#c22d40" },
  { name: "Scaml", type: "markup", slug: "scaml", color: "#bd181a" },
  { name: "Scenic", type: "programming", slug: "scenic", color: "#fdc700" },
  { name: "Scheme", type: "programming", slug: "scheme", color: "#1e4aec" },
  { name: "Scilab", type: "programming", slug: "scilab", color: "#ca0f21" },
  { name: "Self", type: "programming", slug: "self", color: "#0579aa" },
  { name: "ShaderLab", type: "programming", slug: "shaderlab", color: "#222c37" },
  { name: "Shell", type: "programming", slug: "shell", color: "#89e051" },
  { name: "ShellCheck Config", type: "data", slug: "shellcheck-config", color: "#cecfcb" },
  { name: "ShellSession", type: "programming", slug: "shellsession" },
  { name: "Shen", type: "programming", slug: "shen", color: "#120F14" },
  { name: "Sieve", type: "programming", slug: "sieve" },
  { name: "Simple File Verification", type: "data", slug: "simple-file-verification", color: "#C9BFED" },
  { name: "Singularity", type: "programming", slug: "singularity", color: "#64E6AD" },
  { name: "Slang", type: "programming", slug: "slang", color: "#1fbec9" },
  { name: "Slash", type: "programming", slug: "slash", color: "#007eff" },
  { name: "Slice", type: "programming", slug: "slice", color: "#003fa2" },
  { name: "Slim", type: "markup", slug: "slim", color: "#2b2b2b" },
  { name: "Slint", type: "markup", slug: "slint", color: "#2379F4" },
  { name: "SmPL", type: "programming", slug: "smpl", color: "#c94949" },
  { name: "Smali", type: "programming", slug: "smali" },
  { name: "Smalltalk", type: "programming", slug: "smalltalk", color: "#596706" },
  { name: "Smarty", type: "programming", slug: "smarty", color: "#f0c040" },
  { name: "Smithy", type: "programming", slug: "smithy", color: "#c44536" },
  { name: "Snakemake", type: "programming", slug: "snakemake", color: "#419179" },
  { name: "Solidity", type: "programming", slug: "solidity", color: "#AA6746" },
  { name: "Soong", type: "data", slug: "soong" },
  { name: "SourcePawn", type: "programming", slug: "sourcepawn", color: "#f69e1d" },
  { name: "SpiceDB Schema", type: "data", slug: "spicedb-schema", color: "#a5318a" },
  { name: "Spline Font Database", type: "data", slug: "spline-font-database" },
  { name: "Squirrel", type: "programming", slug: "squirrel", color: "#800000" },
  { name: "Stan", type: "programming", slug: "stan", color: "#b2011d" },
  { name: "Standard ML", type: "programming", slug: "standard-ml", color: "#dc566d" },
  { name: "Starlark", type: "programming", slug: "starlark", color: "#76d275" },
  { name: "Stata", type: "programming", slug: "stata", color: "#1a5f91" },
  { name: "StringTemplate", type: "markup", slug: "stringtemplate", color: "#3fb34f" },
  { name: "Stylus", type: "markup", slug: "stylus", color: "#ff6347" },
  { name: "SubRip Text", type: "data", slug: "subrip-text", color: "#9e0101" },
  { name: "SugarSS", type: "markup", slug: "sugarss", color: "#2fcc9f" },
  { name: "SuperCollider", type: "programming", slug: "supercollider", color: "#46390b" },
  { name: "SurrealQL", type: "programming", slug: "surrealql", color: "#ff00a0" },
  { name: "Survex data", type: "data", slug: "survex-data", color: "#ffcc99" },
  { name: "Svelte", type: "markup", slug: "svelte", color: "#ff3e00" },
  { name: "Sway", type: "programming", slug: "sway", color: "#00F58C" },
  { name: "Sweave", type: "prose", slug: "sweave", color: "#198ce7" },
  { name: "Swift", type: "programming", slug: "swift", color: "#F05138" },
  { name: "SystemVerilog", type: "programming", slug: "systemverilog", color: "#DAE1C2" },
  { name: "TI Program", type: "programming", slug: "ti-program", color: "#A0AA87" },
  { name: "TL-Verilog", type: "programming", slug: "tl-verilog", color: "#C40023" },
  { name: "TLA", type: "programming", slug: "tla", color: "#4b0079" },
  { name: "TMDL", type: "data", slug: "tmdl", color: "#f0c913" },
  { name: "TOML", type: "data", slug: "toml", color: "#9c4221" },
  { name: "TSPLIB data", type: "data", slug: "tsplib-data" },
  { name: "TSQL", type: "programming", slug: "tsql", color: "#e38c00" },
  { name: "TSV", type: "data", slug: "tsv", color: "#237346" },
  { name: "TSX", type: "programming", slug: "tsx", color: "#3178c6" },
  { name: "TXL", type: "programming", slug: "txl", color: "#0178b8" },
  { name: "Tact", type: "programming", slug: "tact", color: "#48b5ff" },
  { name: "Talon", type: "programming", slug: "talon", color: "#333333" },
  { name: "Tcl", type: "programming", slug: "tcl", color: "#e4cc98" },
  { name: "Tcsh", type: "programming", slug: "tcsh" },
  { name: "TeX", type: "markup", slug: "tex", color: "#3D6117" },
  { name: "Tea", type: "markup", slug: "tea" },
  { name: "Teal", type: "programming", slug: "teal", color: "#00B1BC" },
  { name: "Terra", type: "programming", slug: "terra", color: "#00004c" },
  { name: "Terraform Template", type: "markup", slug: "terraform-template", color: "#7b42bb" },
  { name: "Texinfo", type: "prose", slug: "texinfo" },
  { name: "Text", type: "prose", slug: "text" },
  { name: "TextGrid", type: "data", slug: "textgrid", color: "#c8506d" },
  { name: "TextMate Properties", type: "data", slug: "textmate-properties", color: "#df66e4" },
  { name: "Textile", type: "prose", slug: "textile", color: "#ffe7ac" },
  { name: "Thrift", type: "programming", slug: "thrift", color: "#D12127" },
  { name: "Toit", type: "programming", slug: "toit", color: "#c2c9fb" },
  { name: "Tor Config", type: "data", slug: "tor-config", color: "#59316b" },
  { name: "Tree-sitter Query", type: "programming", slug: "tree-sitter-query", color: "#8ea64c" },
  { name: "Turing", type: "programming", slug: "turing", color: "#cf142b" },
  { name: "Turtle", type: "data", slug: "turtle" },
  { name: "Twig", type: "markup", slug: "twig", color: "#c1d026" },
  { name: "Type Language", type: "data", slug: "type-language" },
  { name: "TypeScript", type: "programming", slug: "typescript", color: "#3178c6" },
  { name: "TypeSpec", type: "programming", slug: "typespec", color: "#4A3665" },
  { name: "Typst", type: "programming", slug: "typst", color: "#239dad" },
  { name: "Unified Parallel C", type: "programming", slug: "unified-parallel-c", color: "#4e3617" },
  { name: "Unity3D Asset", type: "data", slug: "unity3d-asset", color: "#222c37" },
  { name: "Unix Assembly", type: "programming", slug: "unix-assembly" },
  { name: "Uno", type: "programming", slug: "uno", color: "#9933cc" },
  { name: "UnrealScript", type: "programming", slug: "unrealscript", color: "#a54c4d" },
  { name: "Untyped Plutus Core", type: "programming", slug: "untyped-plutus-core", color: "#36adbd" },
  { name: "UrWeb", type: "programming", slug: "urweb", color: "#ccccee" },
  { name: "V", type: "programming", slug: "v", color: "#4f87c4" },
  { name: "VBA", type: "programming", slug: "vba", color: "#867db1" },
  { name: "VBScript", type: "programming", slug: "vbscript", color: "#15dcdc" },
  { name: "VCL", type: "programming", slug: "vcl", color: "#148AA8" },
  { name: "VHDL", type: "programming", slug: "vhdl", color: "#adb2cb" },
  { name: "Vala", type: "programming", slug: "vala", color: "#a56de2" },
  { name: "Valve Data Format", type: "data", slug: "valve-data-format", color: "#f26025" },
  { name: "Velocity Template Language", type: "markup", slug: "velocity-template-language", color: "#507cff" },
  { name: "Vento", type: "markup", slug: "vento", color: "#ff0080" },
  { name: "Verilog", type: "programming", slug: "verilog", color: "#b2b7f8" },
  { name: "Vim Help File", type: "prose", slug: "vim-help-file", color: "#199f4b" },
  { name: "Vim Script", type: "programming", slug: "vim-script", color: "#199f4b" },
  { name: "Vim Snippet", type: "markup", slug: "vim-snippet", color: "#199f4b" },
  { name: "Visual Basic .NET", type: "programming", slug: "visual-basic-net", color: "#945db7" },
  { name: "Visual Basic 6.0", type: "programming", slug: "visual-basic-6-0", color: "#2c6353" },
  { name: "Volt", type: "programming", slug: "volt", color: "#1F1F1F" },
  { name: "Vue", type: "markup", slug: "vue", color: "#41b883" },
  { name: "Vyper", type: "programming", slug: "vyper", color: "#9F4CF2" },
  { name: "WDL", type: "programming", slug: "wdl", color: "#42f1f4" },
  { name: "WGSL", type: "programming", slug: "wgsl", color: "#1a5e9a" },
  { name: "Wavefront Material", type: "data", slug: "wavefront-material" },
  { name: "Wavefront Object", type: "data", slug: "wavefront-object" },
  { name: "Web Ontology Language", type: "data", slug: "web-ontology-language", color: "#5b70bd" },
  { name: "WebAssembly", type: "programming", slug: "webassembly", color: "#04133b" },
  { name: "WebAssembly Interface Type", type: "data", slug: "webassembly-interface-type", color: "#6250e7" },
  { name: "WebIDL", type: "programming", slug: "webidl" },
  { name: "WebVTT", type: "data", slug: "webvtt" },
  { name: "Wget Config", type: "data", slug: "wget-config" },
  { name: "Whiley", type: "programming", slug: "whiley", color: "#d5c397" },
  { name: "Wikitext", type: "prose", slug: "wikitext", color: "#fc5757" },
  { name: "Win32 Message File", type: "data", slug: "win32-message-file" },
  { name: "Windows Registry Entries", type: "data", slug: "windows-registry-entries", color: "#52d5ff" },
  { name: "Witcher Script", type: "programming", slug: "witcher-script", color: "#ff0000" },
  { name: "Wolfram Language", type: "programming", slug: "wolfram-language", color: "#dd1100" },
  { name: "Wollok", type: "programming", slug: "wollok", color: "#a23738" },
  { name: "World of Warcraft Addon Data", type: "data", slug: "world-of-warcraft-addon-data", color: "#f7e43f" },
  { name: "Wren", type: "programming", slug: "wren", color: "#383838" },
  { name: "X BitMap", type: "data", slug: "x-bitmap" },
  { name: "X Font Directory Index", type: "data", slug: "x-font-directory-index" },
  { name: "X PixMap", type: "data", slug: "x-pixmap" },
  { name: "X10", type: "programming", slug: "x10", color: "#4B6BEF" },
  { name: "XC", type: "programming", slug: "xc", color: "#99DA07" },
  { name: "XCompose", type: "data", slug: "xcompose" },
  { name: "XML", type: "data", slug: "xml", color: "#0060ac" },
  { name: "XML Property List", type: "data", slug: "xml-property-list", color: "#0060ac" },
  { name: "XPages", type: "data", slug: "xpages" },
  { name: "XProc", type: "programming", slug: "xproc" },
  { name: "XQuery", type: "programming", slug: "xquery", color: "#5232e7" },
  { name: "XS", type: "programming", slug: "xs" },
  { name: "XSLT", type: "programming", slug: "xslt", color: "#EB8CEB" },
  { name: "Xmake", type: "programming", slug: "xmake", color: "#22a079" },
  { name: "Xojo", type: "programming", slug: "xojo", color: "#81bd41" },
  { name: "Xonsh", type: "programming", slug: "xonsh", color: "#285EEF" },
  { name: "Xtend", type: "programming", slug: "xtend", color: "#24255d" },
  { name: "YAML", type: "data", slug: "yaml", color: "#cb171e" },
  { name: "YANG", type: "data", slug: "yang" },
  { name: "YARA", type: "programming", slug: "yara", color: "#220000" },
  { name: "YASnippet", type: "markup", slug: "yasnippet", color: "#32AB90" },
  { name: "Yacc", type: "programming", slug: "yacc", color: "#4B6C4B" },
  { name: "Yul", type: "programming", slug: "yul", color: "#794932" },
  { name: "ZAP", type: "programming", slug: "zap", color: "#0d665e" },
  { name: "ZIL", type: "programming", slug: "zil", color: "#dc75e5" },
  { name: "Zeek", type: "programming", slug: "zeek" },
  { name: "ZenScript", type: "programming", slug: "zenscript", color: "#00BCD1" },
  { name: "Zephir", type: "programming", slug: "zephir", color: "#118f9e" },
  { name: "Zig", type: "programming", slug: "zig", color: "#ec915c" },
  { name: "Zimpl", type: "programming", slug: "zimpl", color: "#d67711" },
  { name: "Zmodel", type: "data", slug: "zmodel", color: "#ff7100" },
  { name: "cURL Config", type: "data", slug: "curl-config" },
  { name: "crontab", type: "data", slug: "crontab", color: "#ead7ac" },
  { name: "desktop", type: "data", slug: "desktop" },
  { name: "dircolors", type: "data", slug: "dircolors" },
  { name: "eC", type: "programming", slug: "ec", color: "#913960" },
  { name: "edn", type: "data", slug: "edn" },
  { name: "fish", type: "programming", slug: "fish", color: "#4aae47" },
  { name: "hoon", type: "programming", slug: "hoon", color: "#00b171" },
  { name: "iCalendar", type: "data", slug: "icalendar", color: "#ec564c" },
  { name: "jq", type: "programming", slug: "jq", color: "#c7254e" },
  { name: "kvlang", type: "markup", slug: "kvlang", color: "#1da6e0" },
  { name: "mIRC Script", type: "programming", slug: "mirc-script", color: "#3d57c3" },
  { name: "mcfunction", type: "programming", slug: "mcfunction", color: "#E22837" },
  { name: "mdsvex", type: "markup", slug: "mdsvex", color: "#5f9ea0" },
  { name: "mupad", type: "programming", slug: "mupad", color: "#244963" },
  { name: "nanorc", type: "data", slug: "nanorc", color: "#2d004d" },
  { name: "nesC", type: "programming", slug: "nesc", color: "#94B0C7" },
  { name: "ooc", type: "programming", slug: "ooc", color: "#b0b77e" },
  { name: "pkg-config", type: "data", slug: "pkg-config", color: "#2b5e82" },
  { name: "q", type: "programming", slug: "q", color: "#0040cd" },
  { name: "reStructuredText", type: "prose", slug: "restructuredtext", color: "#141414" },
  { name: "sed", type: "programming", slug: "sed", color: "#64b970" },
  { name: "templ", type: "markup", slug: "templ", color: "#66D0DD" },
  { name: "vCard", type: "data", slug: "vcard", color: "#ee2647" },
  { name: "wisp", type: "programming", slug: "wisp", color: "#7582D1" },
  { name: "xBase", type: "programming", slug: "xbase", color: "#403a40" },
] as const;

const BY_NAME = new Map(LANGUAGES.map((l) => [l.name, l]));

/** Names only — for membership checks (`validate` flags a language not in here). */
export const LANGUAGE_NAMES: ReadonlySet<string> = new Set(BY_NAME.keys());

/** Look up the full ontology entry for a language name. */
export const languageInfo = (name: string): LanguageEntry | undefined => BY_NAME.get(name);

/** Canonical slug for a language (ontology slug, else derived the same way). */
export const languageSlug = (name: string): string =>
  BY_NAME.get(name)?.slug ??
  name.toLowerCase().replace(/\+/g, "p").replace(/#/g, "sharp").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

/** Linguist brand colour for a language, when defined. */
export const languageColor = (name: string): string | undefined => BY_NAME.get(name)?.color;
