#!/usr/bin/env bun
// synoptic-github — regenerate a profile README from your GitHub corpus.
// Pipeline: fetch → normalize → validate (Zod contract) → render (pure, deterministic).
// Grouped by self-labeled topic; forks and archived repos excluded.
//
// Env:
//   GITHUB_TOKEN       required — reads your repos
//   GROUP_BY           topic | language | none   (default: topic)
//   OUT                output path               (default: README.md)
//   SOURCE_DATE_EPOCH  source commit time (s) for a reproducible stamp (default: 0)
//   GITHUB_SHA         commit, recorded as provenance.version
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Repo, Corpus, type Provenance } from "./schema.ts";

const TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
if (!TOKEN) { console.error("✗ set GITHUB_TOKEN"); process.exit(1); }
const GROUP_BY = (process.env.GROUP_BY || "topic").toLowerCase();
const OUT = process.env.OUT || "README.md";
const here = dirname(fileURLToPath(import.meta.url));

async function gh(path: string, init?: RequestInit) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${TOKEN}`, Accept: "application/vnd.github+json", "User-Agent": "synoptic-github", ...(init?.headers ?? {}) },
  });
  if (!res.ok) throw new Error(`${path} → ${res.status} ${await res.text()}`);
  return res.json();
}
async function ghAll(path: string): Promise<any[]> {
  const out: any[] = [];
  for (let page = 1; ; page++) {
    const batch = (await gh(`${path}${path.includes("?") ? "&" : "?"}per_page=100&page=${page}`)) as any[];
    out.push(...batch);
    if (batch.length < 100) return out;
  }
}

async function langEmojis(): Promise<Record<string, string>> {
  try {
    const txt = await readFile(join(here, "action", "language_emojis.txt"), "utf8");
    return Object.fromEntries(txt.split("\n").map((l) => l.split(":")).filter((p) => p.length === 2).map(([k, v]) => [k.trim(), v.trim()]));
  } catch { return {}; }
}

// ---- fetch + normalize -------------------------------------------------------
const user = (await gh("/user")) as { name?: string; login: string };
const raw = (await ghAll("/user/repos?affiliation=owner&visibility=public")) as any[];
const repos = raw
  .filter((r) => !r.fork && !r.archived)
  .map((r) =>
    Repo.parse({
      name: r.name, fullName: r.full_name, url: r.html_url, description: r.description ?? null,
      language: r.language ?? null, topics: r.topics ?? [], stars: r.stargazers_count, pushedAt: r.pushed_at,
    }),
  )
  // deterministic order: stars desc, then most-recent push, then name
  .sort((a, b) => b.stars - a.stars || (a.pushedAt < b.pushedAt ? 1 : a.pushedAt > b.pushedAt ? -1 : 0) || a.name.localeCompare(b.name));

const provenance: Provenance = {
  tool: "synoptic-github",
  version: (process.env.GITHUB_SHA ?? "dev").slice(0, 7),
  owner: user.login,
  sourceEpoch: Number(process.env.SOURCE_DATE_EPOCH ?? 0) || 0,
};

// ---- validate the contract ---------------------------------------------------
const corpus = Corpus.parse({ provenance, owner: user.login, name: user.name || user.login, repos });

// ---- render (pure function of the validated corpus) --------------------------
const emojis = await langEmojis();
const langs = Object.entries(
  corpus.repos.reduce<Record<string, number>>((m, r) => (r.language ? ((m[r.language] = (m[r.language] || 0) + 1), m) : m), {}),
).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));

const line = (r: Repo) =>
  `- [${r.name}](${r.url})` + (r.description ? ` — ${r.description}` : "") + (r.language ? ` \`${emojis[r.language] ?? ""}${r.language}\`` : "");

const out: string[] = [
  `# ${corpus.name}`,
  `\`${corpus.owner}\` · ${corpus.repos.length} public repositories · ${langs.slice(0, 4).map(([l, n]) => `${l} ${n}`).join(" · ")}`,
];

if (GROUP_BY === "none") {
  out.push(corpus.repos.map(line).join("\n"));
} else if (GROUP_BY === "language") {
  for (const [lang] of langs) {
    const inLang = corpus.repos.filter((r) => r.language === lang);
    if (inLang.length) out.push(`## ${emojis[lang] ?? ""}${lang}\n\n${inLang.map(line).join("\n")}`);
  }
} else {
  const groups = new Map<string, Repo[]>();
  const other: Repo[] = [];
  for (const r of corpus.repos) (r.topics[0] ? (groups.get(r.topics[0]) ?? groups.set(r.topics[0], []).get(r.topics[0])!) : other).push(r);
  for (const [topic, rs] of [...groups].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0])))
    out.push(`## ${topic}\n\n${rs.map(line).join("\n")}`);
  if (other.length) out.push(`## other\n\n${other.map(line).join("\n")}`);
}

// Provenance footer — reproducible (source commit, not wall-clock).
const stamp = corpus.provenance.sourceEpoch ? ` · ${new Date(corpus.provenance.sourceEpoch * 1000).toISOString().slice(0, 10)}` : "";
out.push(`<sub>Generated by <a href="https://github.com/bdelanghe/synoptic-github">synoptic-github</a> @ ${corpus.provenance.version}${stamp} — grouped by self-labeled topic.</sub>`);

await writeFile(OUT, out.join("\n\n") + "\n");
console.log(`✓ wrote ${OUT} — ${corpus.repos.length} repos, grouped by ${GROUP_BY}, stamped ${corpus.provenance.version}`);
