#!/usr/bin/env bun
// synoptic-github v2 — regenerate a profile README from your GitHub corpus.
// Clean + meta-analysed: grouped by self-labeled topic (the per-repo contract),
// with a language summary. Forks and archived repos excluded by default.
//
// Env:
//   GITHUB_TOKEN  required — a token that can read your repos
//   GROUP_BY      topic | language | none   (default: topic)
//   OUT           output path               (default: README.md)
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
if (!TOKEN) { console.error("✗ set GITHUB_TOKEN"); process.exit(1); }
const GROUP_BY = (process.env.GROUP_BY || "topic").toLowerCase();
const OUT = process.env.OUT || "README.md";
const here = dirname(fileURLToPath(import.meta.url));

type Repo = {
  name: string; full_name: string; html_url: string; description: string | null;
  language: string | null; topics: string[]; fork: boolean; archived: boolean;
  private: boolean; stargazers_count: number; pushed_at: string;
};

async function ghAll(path: string): Promise<any[]> {
  const out: any[] = [];
  for (let page = 1; ; page++) {
    const res = await fetch(
      `https://api.github.com${path}${path.includes("?") ? "&" : "?"}per_page=100&page=${page}`,
      { headers: { Authorization: `Bearer ${TOKEN}`, Accept: "application/vnd.github+json", "User-Agent": "synoptic-github" } },
    );
    if (!res.ok) throw new Error(`${path} → ${res.status} ${await res.text()}`);
    const batch = (await res.json()) as any[];
    out.push(...batch);
    if (batch.length < 100) return out;
  }
}

async function langEmojis(): Promise<Record<string, string>> {
  try {
    const txt = await readFile(join(here, "action", "language_emojis.txt"), "utf8");
    const m: Record<string, string> = {};
    for (const line of txt.split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) m[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
    return m;
  } catch { return {}; }
}

const user = (await (await fetch("https://api.github.com/user", {
  headers: { Authorization: `Bearer ${TOKEN}`, "User-Agent": "synoptic-github" },
})).json()) as { name?: string; login: string };

const repos = ((await ghAll("/user/repos?affiliation=owner&visibility=public")) as Repo[])
  .filter((r) => !r.fork && !r.archived)
  .sort((a, b) => b.stargazers_count - a.stargazers_count || +new Date(b.pushed_at) - +new Date(a.pushed_at));

const emojis = await langEmojis();
const langs = Object.entries(repos.reduce<Record<string, number>>((m, r) => {
  if (r.language) m[r.language] = (m[r.language] || 0) + 1;
  return m;
}, {})).sort((a, b) => b[1] - a[1]);

const line = (r: Repo) =>
  `- [${r.name}](${r.html_url})` +
  (r.description ? ` — ${r.description}` : "") +
  (r.language ? ` \`${emojis[r.language] ?? ""}${r.language}\`` : "");

const sections: string[] = [];
const title = user.name || user.login;
sections.push(`# ${title}`);
sections.push(`\`${user.login}\` · ${repos.length} public repositories · ${langs.slice(0, 4).map(([l, n]) => `${l} ${n}`).join(" · ")}`);

if (GROUP_BY === "none") {
  sections.push(repos.map(line).join("\n"));
} else if (GROUP_BY === "language") {
  for (const [lang] of langs) {
    const inLang = repos.filter((r) => r.language === lang);
    if (inLang.length) sections.push(`## ${emojis[lang] ?? ""}${lang}\n\n${inLang.map(line).join("\n")}`);
  }
} else {
  // group by primary (first) topic — the self-labeled contract
  const groups = new Map<string, Repo[]>();
  const other: Repo[] = [];
  for (const r of repos) {
    const t = r.topics?.[0];
    if (t) (groups.get(t) ?? groups.set(t, []).get(t)!).push(r);
    else other.push(r);
  }
  const ordered = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [topic, rs] of ordered) sections.push(`## ${topic}\n\n${rs.map(line).join("\n")}`);
  if (other.length) sections.push(`## other\n\n${other.map(line).join("\n")}`);
}

sections.push(`<sub>Generated by <a href="https://github.com/bdelanghe/synoptic-github">synoptic-github</a> — grouped by self-labeled topic.</sub>`);

await writeFile(OUT, sections.join("\n\n") + "\n");
console.log(`✓ wrote ${OUT} — ${repos.length} repos, grouped by ${GROUP_BY}`);
